logging:
  level:
    root: info
    com.se.back: debug
  file:
    path: logs
  config: classpath:logback-spring.xml
spring:
  datasource:
    url: jdbc:mysql://192.168.0.111:3306/mark?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 192.168.0.111
    database: 2
    port: 6380
  mvc:
    throw-exception-if-no-handler-found: true
  aop:
    proxy-target-class: true

elasticsearch:
  ip:
    single: 39.104.65.29:9289
    cluster: 192.168.0.111:9288,192.168.0.111:9288,192.168.0.111:9288

org:
  neo4j:
    driver:
      uri: bolt://39.104.65.29:7687
      authentication:
        username: neo4j
        password: 123456781
