logging:
  level:
    root: info
    com.se.back: info
  file:
    path: logs
  config: classpath:logback-spring.xml

spring:
  datasource:
    url: jdbc:mysql://rm-hp30vh614j632p5ki.mysql.huhehaote.rds.aliyuncs.com:3306/mark?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: r-hp3ojxc6skjau81163.redis.huhehaote.rds.aliyuncs.com
    database: 100
    port: 6379
  mvc:
    throw-exception-if-no-handler-found: true
  aop:
    proxy-target-class: true
  resources:
    add-mappings: false

elasticsearch:
  ip:
    single: 172.24.42.226:9288
    cluster: 172.24.42.223:9288,172.24.42.224:9288,172.24.42.225:9288

org:
  neo4j:
    driver:
      uri: bolt://172.24.42.226:7687
      authentication:
        username: neo4j
        password: 123456781
server:
  port: 9290